### ISSUE TITLE
when select a file  res : {"fileCopyUri":"content://com.android.providers.media.documents/document/image%3A5830","size":11789471,"name":"IMG_20210331_190932.jpg","type":"image/jpeg","uri":"content://com.android.providers.media.documents/document/image%3A5830"} server side when send this data  only get a uri not a image ....i am apply fromdata() but still not work...

### ISSUE THREAD

**Issue by rajan-keypress** [thejump/react-native-document-picker#1]

**Comment by Rajan-Savaliya-spt** [comment]
var myHeaders = new Headers();
      myHeaders.append('Content-Type', 'application/json');
      myHeaders.append('Content-Type', 'multipart/form-data');
      const fileToUpload = singleFile;
      const data = new FormData();
      data.append('name', 'Image Upload');
      data.append('file_attachment', fileToUpload);

      var raw = JSON.stringify({
        jsonrpc: '2.0',
        method: 'call',
        id: 921359310,
        params: {method: 'list', service: 'db', args: {}},
        headers: headers,
        logourl: logourl,
        logourl2: logourl2,
        primarycolor: primaryColor,
        secondarycolor: secondarycolor,
        user: user,
        odoourl: odoourl,
        email: email,
        mobilenumber: mobilenumber,
        lottiejsonfiles: data
      });

      var requestOptions = {
        method: 'POST',
        headers: myHeaders,
        body: raw,
        redirect: 'follow',
      };

      fetch(`${WEB_URL}/app/crm_debrand_req`, requestOptions)

**Comment by rajan-keypress** [comment]
i follow this blog.......
`https://aboutreact.com/file-uploading-in-react-native/`
